POST http://localhost:5147/api/Todo
content-type: application/json

{
    "name": "hello 02",
    "IsComplete": false
}

###

GET http://localhost:5147/api/Todo
###

GET http://localhost:5147/api/Todo/complete

###

GET http://localhost:5147/api/Todo/a05ffa75-4b34-42d1-aba2-755497302278

###

PUT http://localhost:5147/api/Todo
content-type: application/json

{
    "id":"a05ffa75-4b34-42d1-aba2-755497302278",
    "name": "hello abc"
}

###

DELETE  http://localhost:5147/api/Todo/a05ffa75-4b34-42d1-aba2-755497302278