POST http://localhost:5147/todoItems
content-type: application/json

{
    "name": "hello 02",
    "IsComplete": false
}

###

GET http://localhost:5147/todoItems

###

GET http://localhost:5147/todoItems/cd6295ac-4894-4ccc-8ad9-fb3aa18f565b

###
GET http://localhost:5147/todoItems/complete

###

PUT http://localhost:5147/todoItems/3573c9ab-4c48-433b-8487-be39b2588e36
content-type: application/json

{
    "name": "hello a"
}

###

DELETE  http://localhost:5147/todoItems/e267231d-686b-49d7-9d74-12652dc027b1